### ISSUE TITLE
Wrong link? 

### ISSUE THREAD

**Issue by amandamcg** [martinkorelic/joplin-plugin-quick-html-tags#1]
Thanks for making this. FYI, your link in the README for `Some of my personal predefined custom tags can be found here.` goes to your theme page which seems to be a mistake. Would love to see some examples of how you use this.

**Comment by martinkorelic** [comment]
Sorry for the late response, the link goes to my style css file which contains the styling for these tags.
Just like the gif in README.md shows an example of me using a custom tag and the styles for that tag is written in that css file.
Go through the css file to discover other custom tags.
