### ISSUE TITLE
[support question and idea] how to define color tags?

### ISSUE THREAD

**Issue by omega3** [martinkorelic/joplin-plugin-quick-html-tags#2]
Can you please explain how to define html  tags for coloring text?

This 
`<span style="color:orange">example text</span>`
colors text but I don't know what part of it to paste into your add-on to define tag so that it can wrap text and make it orange.

Would be nice to have some configuration file to have some predefined html or css classes with custom names so that when I press Ctrl+H it displays me these names, like orange and clicking on "add" just wrap text in this class and makes it colorful. I imagine this could work in the same way as icons with bold, italic, etc.

Next example: I'd like to be able to wrap text with blockquote boxes and when I choose in add-on dialog blockquote it gives me this effect:
https://i.imgur.com/hk6yKau.png

Other sample css classes that I would like to use
https://codyhouse.co/demo/animated-headlines/index.html

I am sure other Joplin users would love it. Not all users are markdown fans. Some, like myself use it just as a notebook.

**Comment by martinkorelic** [comment]
For the moment I have not implemented any type of adding attributes to tags. You can only predefine tag names in the settings, which allow you to quickly add them from the dropdown menu.

But there is a workaround for this of what you're trying to achieve (for the orange wrapping part).

Open up your `userstyle.css` under profile directory and define a new custom tag:
```css
orange {
    color: orange;
}
```
And then add the "orange" to the Quick HTML settings. Now everytime you will Ctrl + H and select "orange", it will allow you to quickly wrap text in orange with that custom tag.

**Comment by martinkorelic** [comment]
I realize that it's a very static option as it would need you to add all custom tags for colours, and it would be much easier to just type and add a colour inside the popup box. As of right now, I have not even started on working on this, but everyone is welcome to contribute to this and add the implementation via PR. :)

**Comment by NeerajGartia21** [comment]
can I work on this issue @martinkorelic

**Comment by martinkorelic** [comment]
> can I work on this issue @martinkorelic

If you want to, you can try.

**Comment by NeerajGartia21** [comment]
if the user adds color.red tag in the input box then we can replace the selected section by -
`<div style="color:red">sometext</div>`
Is it a good approach? @martinkorelic

**Comment by martinkorelic** [comment]
> if the user adds color.red tag in the input box then we can replace the selected section by - `<div style="color:red">sometext</div>` Is it a good approach? @martinkorelic

Perhaps we would generalize this, so that the Quick HTML modal window would have a new input box (or list menu), where the user can specify attributes, which can be added to the html element.

For example: If a user types in the _new style attributes box_ "color:red" it would be added to the style attribute.
However, a user might add more style attributes, so we would allow the user to add another attribute, let's say "font-size:large".

Then the expected generated result would be
`<div style="color:red;font-size:13px">sometext</div>`

**Comment by NeerajGartia21** [comment]
Should we impliment this?

**Comment by NeerajGartia21** [comment]
Should I implement this?

**Comment by martinkorelic** [comment]
If you want you can get a start on it, feature like that would be needed.

**Comment by NeerajGartia21** [comment]
I will start working on this.

**Comment by NeerajGartia21** [comment]
https://user-images.githubusercontent.com/80708727/160762566-2fbabcab-5541-42ea-8637-f1900a325cbc.mp4

Please suggest any changes or improvement @martinkorelic

**Comment by NeerajGartia21** [comment]
https://user-images.githubusercontent.com/80708727/160762868-0ad8ad23-380f-445f-9395-7b3d3fb4b6d7.mp4

Is this fine @martinkorelic ?
please give suggestions.

**Comment by martinkorelic** [comment]
Now added in v0.2.0.
Thanks @NeerajGartia21 !

**Comment by NeerajGartia21** [comment]
Thanks for merging the PR @martinkorelic . Looking forward to contribute to more issues.
